"""f

Revision ID: 782648f22dac
Revises: 
Create Date: 2022-02-13 17:40:15.478740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782648f22dac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
