"""fdd

Revision ID: eff50d99e4f7
Revises: 782648f22dac
Create Date: 2022-02-13 19:07:23.656785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff50d99e4f7'
down_revision = '782648f22dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
